version: 2

models:
  - name: stg_users
    description: "Stage raw user data with days since signup"
    columns:
      - name: user_id
        description: "Unique user ID"
        tests:
          - unique
          - not_null

      - name: user_email
        description: "User's email address"
        tests:
          - not_null:
              arguments: {}
              severity: warn

      - name: user_status
        description: "User's account status"
        tests:
          - accepted_values:
              arguments:
                values: ['active', 'inactive', 'pending']

  - name: stg_user_profiles
    description: "Stage user profiles linked to users"
    columns:
      - name: profile_id
        description: "Primary key of the user_profiles table"
        
      - name: user_id
        description: "Foreign key to users.user_id"
        tests:
          - relationships:
              arguments:
                to: ref('stg_users')
                field: user_id
              
      - name: profile_name
        description: "Name of the user's profile"
