version: 2

models:
  - name: customers
    description: "Customer dimension table"
    columns:
      - name: id
        description: "Primary key"
        tests:
          - unique
          - not_null

      - name: email
        description: "Customer email address"
        tests:
          - not_null
          - valid_email  # custom test — assumed this is defined as a custom data test elsewhere

      - name: country
        description: "Customer country"
        tests:
          - accepted_values:
              arguments:
                values: ['USA', 'Canada', 'UK']

  - name: orders
    description: "Order fact table"
    columns:
      - name: customer_id
        description: "FK to customers"
        tests:
          - relationships:
              arguments:
                to: ref('customers')
                field: id
